version: '3.6'
services:
  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: redwoodblog
    image: 'postgres:14-alpine'
    ports:
      - 5432:5432
    volumes:
      - './data/postgres:/var/lib/postgresql/data'

